INIT:
SELECT
 TO_CHAR(SYSDATE,'yyyy-mm-dd') INGENDAT,
 TO_CHAR(TO_DATE('^$IN_DATA^','YYYYMM'),'YYYYMM') INDATA, 
 NVL('^$IN_FIRMA^', 'AUCHAN') INFIRMA,
 NVL('^$IN_CENPLA^', '%') INCENPLA,
 NVL('^$IN_LOK^', '%') INLOK,
 CASE '^$IN_TOP^'
	when 'TAK' then 'true'
	when 'NIE' then 'false'
	else 'false'
 END AS INTOP	
FROM DUAL; 

CNT:
SELECT
	B.CDPAVE VCNTPOS,
	B.CDCOMP VCNTNAME,
	(SELECT X.LIBABR FROM ZD00 Y, ZD01 X WHERE Y.NUDOSS = X.NUDOSS AND Y.SOCDOS = 'PPL' AND Y.CDSTCO = 'DL2' AND Y.CDCODE = B.CDCOMP) VCNTLAB,
	0 VCNTSUM
FROM ZD00 A, ZDCG B
WHERE
	A.SOCDOS = 'PPL' AND A.CDSTCO = 'DRL' AND A.CDCODE = '90'
	AND A.NUDOSS = B.NUDOSS
ORDER BY CDPAVE;

	
PITEM:
SELECT
	CDELEM VPITEM,
	TYALIM VTYP,
	CDSIGN VSIGN
FROM ZDBV A
WHERE
	A.NUDOSS = (SELECT NUDOSS FROM ZD00 WHERE SOCDOS = 'PPL' AND CDSTCO = 'DL2' AND CDCODE = '^$VCNTNAME^');


PSUM:
SELECT 
  TO_CHAR(
    TO_NUMBER('^$VCNTSUM^','FM9999999990.90') + TOMEK.PAYITEM_ZX8K('^$INFIRMA^','^$INCENPLA^','^$INLOK^','^$INTOP^','^$VTYP^','^$VSIGN^','^$VPITEM^','^$INDATA^')
    ,'FM9999999990.90')	VCNTSUM
FROM DUAL;

WIERSZ:
SELECT
  '<TR><TD align="center">'||'^$VCNTNAME^'||'</TD><TD align="center">'||'^$VCNTLAB^'||'</TD><TD align="right">'||'^$VCNTSUM^'||'</TD></TR>' V_WIERSZ
FROM DUAL
WHERE TO_NUMBER('^$VCNTSUM^','FM9999999990.00') <> 0 ;

WIERSZ_CSV:
SELECT
  '^$VCNTNAME^'||';'||'^$VCNTLAB^'||';'||'^$VCNTSUM^'||';' V_WIERSZ
FROM DUAL
WHERE TO_NUMBER('^$VCNTSUM^','FM9999999990.00') <> 0 ;  

WIERSZ_RTF:
SELECT
  '^$VCNTNAME^' VCNTNAME,
  '^$VCNTLAB^' VCNTLAB,
  '^$VCNTSUM^' VCNTSUM
FROM DUAL
WHERE TO_NUMBER('^$VCNTSUM^','FM9999999990.00') <> 0 ;  