VERSION 2

INIT:
SELECT 
 NVL(^$IN_DATA^,'2013/01/01') PV_DATA FROM DUAL;

PRACOWNIK:
SELECT DISTINCT
    ZA00.NUDOSS NUDOSS,
    RTRIM(ZA05.NOMUSU) IMIE,
    RTRIM(ZA05.PRENOM) NAZWISKO		
FROM ZA00, ZA05, ZAES
WHERE ZA00.NUDOSS = ZA05.NUDOSS
  AND ZA00.NUDOSS = ZAES.NUDOSS
  AND ZAES.DATENT = TO_DATE('^$PV_DATA^','YYYY/MM/DD');
