VERSION 2

INIT:
SELECT 
 NVL('2013/11/09','2013/01/01') PV_DATA
FROM DUAL;

PRACOWNIK:
SELECT 
    '786232' ZA00_NUDOSS,  		
    'Tadam' NAZWISKO,
    'Adam' IMIE
FROM DUAL WHERE TO_DATE('^$PV_DATA^','YYYY/MM/DD') = TO_DATE('^$PV_DATA^','YYYY/MM/DD');
