

INIT:
SELECT
 NVL('^$IN_FIRM^','AUCHAN') INFIRMA, 
 NVL('^$IN_MIES^',TO_CHAR(SYSDATE,'RRRRMM')) PV_MIES,
 NVL('^$IN_IMIE^','Jaroslaw') PV_IMIE,
 NVL('^$IN_NAZWISKO^','Kowalczyk') PV_NAZWISKO,
 TO_CHAR(SYSDATE,'YYYY-MM-DD') V_DATA_W,
 '<TD>0.000</TD><TD>0.000</TD>' C_POL258,
 '<td><b>0.000</b></td><td><b>0.000</b></td>'  SUM_POL258; 



FIRMA:
SELECT
  NIP F_NIP,
  REGON F_REGON,
  NAZWA_FIRMY F_NAZWA_FIRMY,
  KRAJ F_KRAJ,
  WOJEWODZTWO F_WOJEWODZTWO,
  POWIAT F_POWIAT,
  GMINA F_GMINA,
  ULICA F_ULICA,
  NR_DOMU F_NR_DOMU,
  NR_LOKALU F_NR_LOKALU,
  MIEJSCOWOSC F_MIEJSCOWOSC,
  KOD_POCZTOWY F_KOD_POCZTOWY,
  POCZTA F_POCZTA,
 SUBSTR('^$PV_MIES^',1,4)||'-'||SUBSTR('^$PV_MIES^',5,2) V_MIES,
 TOMEK.GENRAP_DDL('DECLARE A NUMBER; BEGIN A:=TOMEK.FRAP121_ALL('||SUBSTR('^$PV_MIES^',1,4)||','||SUBSTR('^$PV_MIES^',5,2)||','||'''^$IN_FIRM^'''||'); END;') wyniki;