# PRZYK£ADOWA LINIA PARAMETRÓW:    
# IN_LOKAL=''&IN_NR_EW=''&IN_OKRES_OD=''&IN_OKRES_DO=''&IN_DATA_W=''&IN_ROKMIES=''
# ver 1: UTWORZONO 2015-11-25 TK
# ver 2: Modyfikacja form.xml, usuniecie logo Real
# ver 3:
# ver 4: Dodanie POD i ZZZ

INIT:
SELECT
  NVL('^$IN_FIRM^', 'AUCHAN') V_FIRMA,
  NVL(SUBSTR('^$IN_LOKAL^', 1, 6),'%') V_LOKAL,
  NVL('^$IN_NR_EW^','%') V_NR_EW,    
  NVL('^$IN_DATA_W^',TO_CHAR(SYSDATE,'YYYY-MM-DD')) DATA_W,
  NVL('^$IN_ROKMIES^','299912') P_ROKMIES,
  NVL(''||'^$IN_PROFILE^'||'','SELECT NUDOSS FROM ZA00') P_PROFILE,
  '^$IN_USER^' P_USER,
  0 VROW
FROM DUAL
;

FIRMA: 
SELECT
  NIP F_NIP,
  REGON F_REGON,
  NAZWA_PIT F_NAZWA_FIRMY,
  KRAJ F_KRAJ,
  WOJEWODZTWO F_WOJEWODZTWO,
  POWIAT F_POWIAT,
  GMINA F_GMINA,
  ULICA F_ULICA,
  NR_DOMU F_NR_DOMU,
  NR_LOKALU F_NR_LOKALU,
  MIEJSCOWOSC F_MIEJSCOWOSC,
  KOD_POCZTOWY F_KOD_POCZTOWY,
  POCZTA F_POCZTA,
  PKD V_PKD
FROM TOMEK.FIRMY
WHERE FIRMA = '^$V_FIRMA^'
;

test:
select count(1) v_ile from zazz a where a.nudoss in (^$P_PROFILE^);

PRACOWNIK:
SELECT ROWNUM VROW,
    A.NUDOSS ZA00_NUDOSS,
	A.SOCDOS V_SOCDOS,
	A.MATCLE P_NR_EW,
    TRIM(B.NOMUSU) P_NAZWISKO,
    TRIM(B.PRENOM) P_IMIE,
	DECODE(B.QUALIT,'1', 'Pan', '2', 'Pani', '3', 'Pani', 'osoba') P_PLEC,
    TRIM(D.NUMERO) P_PESEL,
    NVL(TRIM(E.NOMVOI),' ') P_ULICA,
    TRIM(E.NOVOIE)||DECODE(TRIM(E.PORTEX),NULL,'','/'||TRIM(E.PORTEX)) P_NR_DOMU,
    DECODE(TRIM(E.COMMUN), TRIM(E.VILLEX),TRIM(E.VILLEX),TRIM(E.VILLEX)||', '||TRIM(E.COMMUN)) P_MIEJSCOWOSC,
    TRIM(E.CODPOS) P_KOD_MSC,
    TO_CHAR(H.DATENT, 'YYYY-MM-DD') P_DATA_OD,
    TRIM((SELECT Z.LIBLON  FROM ZAKA X, ZD00 Y, ZD01 Z 
	              WHERE X.NUDOSS = A.NUDOSS AND TO_DATE('^$DATA_W^','YYYY-MM-DD') BETWEEN X.DATAOD AND X.DATADO
				    AND X.RODZUM = Y.CDCODE AND Y.SOCDOS = DECODE(A.SOCDOS,'POL','PPL','REL','PRL') AND Y.CDREGL = DECODE(A.SOCDOS,'POL','PPL','REL','PRL') AND Y.CDSTCO = 'LAW' AND Y.NUDOSS = Z.NUDOSS)) P_R_UMOWA,
    F.DIVUPP ||'/'||F.DIVLOW P_WYM_ET
FROM ZA00 A, ZA05 B, ZANA C, ZANT D, ZAKO E, ZAKN F, ZAES H, ZAZZ I, TOMEK.LOKALIZACJE L
WHERE A.MATCLE LIKE '^$V_NR_EW^'
  AND A.NUDOSS IN (^$P_PROFILE^)
  AND A.NUDOSS = I.NUDOSS
  AND A.NUDOSS = B.NUDOSS
  AND A.NUDOSS = C.NUDOSS
  AND A.NUDOSS = D.NUDOSS
  AND A.NUDOSS = E.NUDOSS
  AND E.FLAG01 = 'X'
  AND A.NUDOSS = F.NUDOSS
  AND TO_DATE('^$DATA_W^','YYYY-MM-DD') BETWEEN F.DATEFF AND F.DATXXX
  AND A.NUDOSS = H.NUDOSS
  AND TO_DATE('^$DATA_W^','YYYY-MM-DD') BETWEEN H.DATENT AND H.DATSOR
  AND L.FIRMA = '^$V_FIRMA^'
  AND L.LOKALIZACJA LIKE '^$V_LOKAL^'
  AND TRIM(I.CENPAI) = L.LOKALIZACJA
  ORDER BY A.MATCLE;

DATA1:
SELECT
    DECODE('^$P_ROKMIES^','299912',NVL((SELECT TRIM(MAX(Z.PERPAI)) FROM ZX00 Z WHERE Z.NUGEST = ^$ZA00_NUDOSS^),TO_CHAR(SYSDATE,'YYYYMM')),'^$P_ROKMIES^') V_PM1
FROM DUAL;

DATY:
SELECT
    NVL(TO_CHAR(ADD_MONTHS(  TO_DATE('^$V_PM1^','YYYYMM'),-1),'YYYYMM'),TO_CHAR(ADD_MONTHS(  TO_DATE((SELECT TRIM(MAX(Z.PERPAI)) FROM ZX00 Z WHERE Z.NUGEST = ^$ZA00_NUDOSS^),'YYYYMM'), -1),'YYYYMM')) V_PM2,
    NVL(TO_CHAR(ADD_MONTHS(  TO_DATE('^$V_PM1^','YYYYMM'),-2),'YYYYMM'),TO_CHAR(ADD_MONTHS(  TO_DATE((SELECT TRIM(MAX(Z.PERPAI)) FROM ZX00 Z WHERE Z.NUGEST = ^$ZA00_NUDOSS^),'YYYYMM'), -2),'YYYYMM')) V_PM3
FROM DUAL;
  
DANE:
SELECT
    TO_CHAR(-1 * TOMEK.PIT_WAROSC_ZX8K_NUDOSS('ZZZ', '^$V_PM1^', ^$ZA00_NUDOSS^),'FM9999999990.00') PZZZ_1, 
	TO_CHAR(-1 * TOMEK.PIT_WAROSC_ZX8K_NUDOSS('ZZZ', '^$V_PM2^', ^$ZA00_NUDOSS^),'FM9999999990.00') PZZZ_2, 
	TO_CHAR(-1 * TOMEK.PIT_WAROSC_ZX8K_NUDOSS('ZZZ', '^$V_PM3^', ^$ZA00_NUDOSS^),'FM9999999990.00') PZZZ_3,

    TO_CHAR(-1 * TOMEK.PIT_WAROSC_ZX8K_NUDOSS('POD', '^$V_PM1^', ^$ZA00_NUDOSS^),'FM9999999990.00') PPOD_1,
	TO_CHAR(-1 * TOMEK.PIT_WAROSC_ZX8K_NUDOSS('POD', '^$V_PM2^', ^$ZA00_NUDOSS^),'FM9999999990.00') PPOD_2,  
    TO_CHAR(-1 * TOMEK.PIT_WAROSC_ZX8K_NUDOSS('POD', '^$V_PM3^', ^$ZA00_NUDOSS^),'FM9999999990.00') PPOD_3,
 
    TO_CHAR(TOMEK.PIT_WAROSC_ZX8K_NUDOSS('A30', '^$V_PM1^', ^$ZA00_NUDOSS^),'FM9999999990.00') PA30_1, 
	TO_CHAR(TOMEK.PIT_WAROSC_ZX8K_NUDOSS('A30', '^$V_PM2^', ^$ZA00_NUDOSS^),'FM9999999990.00') PA30_2, 
	TO_CHAR(TOMEK.PIT_WAROSC_ZX8K_NUDOSS('A30', '^$V_PM3^', ^$ZA00_NUDOSS^),'FM9999999990.00') PA30_3,

    TO_CHAR(TOMEK.PIT_WAROSC_ZX8K_NUDOSS('KPR', '^$V_PM1^', ^$ZA00_NUDOSS^),'FM9999999990.00') PKPR_1,
	TO_CHAR(TOMEK.PIT_WAROSC_ZX8K_NUDOSS('KPR', '^$V_PM2^', ^$ZA00_NUDOSS^),'FM9999999990.00') PKPR_2,  
    TO_CHAR(TOMEK.PIT_WAROSC_ZX8K_NUDOSS('KPR', '^$V_PM3^', ^$ZA00_NUDOSS^),'FM9999999990.00') PKPR_3,

    TO_CHAR(-1 * (
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('ZEM', '^$V_PM1^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('ZRE', '^$V_PM1^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('ZCH', '^$V_PM1^', ^$ZA00_NUDOSS^)),'FM9999999990.00') PZUS_1,
	TO_CHAR(-1 * (
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('ZEM', '^$V_PM2^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('ZRE', '^$V_PM2^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('ZCH', '^$V_PM2^', ^$ZA00_NUDOSS^)),'FM9999999990.00') PZUS_2,
    TO_CHAR(-1 * (
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('ZEM', '^$V_PM3^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('ZRE', '^$V_PM3^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('ZCH', '^$V_PM3^', ^$ZA00_NUDOSS^)),'FM9999999990.00') PZUS_3,
	
    TO_CHAR(TOMEK.PIT_WAROSC_ZX8K_NUDOSS('A60', '^$V_PM1^', ^$ZA00_NUDOSS^),'FM9999999990.00') PA60_1, 
	TO_CHAR(TOMEK.PIT_WAROSC_ZX8K_NUDOSS('A60', '^$V_PM2^', ^$ZA00_NUDOSS^),'FM9999999990.00') PA60_2, 
	TO_CHAR(TOMEK.PIT_WAROSC_ZX8K_NUDOSS('A60', '^$V_PM3^', ^$ZA00_NUDOSS^),'FM9999999990.00') PA60_3,
	
    TO_CHAR(TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S02', '^$V_PM1^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S05', '^$V_PM1^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S07', '^$V_PM1^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S10', '^$V_PM1^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S11', '^$V_PM1^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S13', '^$V_PM1^', ^$ZA00_NUDOSS^) -
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('SPP', '^$V_PM1^', ^$ZA00_NUDOSS^)
			,'FM9999999990.00') PINNE_1,
	TO_CHAR(TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S02', '^$V_PM2^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S05', '^$V_PM2^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S07', '^$V_PM2^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S10', '^$V_PM2^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S11', '^$V_PM2^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S13', '^$V_PM2^', ^$ZA00_NUDOSS^) -
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('SPP', '^$V_PM2^', ^$ZA00_NUDOSS^)
			,'FM9999999990.00') PINNE_2,
    TO_CHAR(TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S02', '^$V_PM3^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S05', '^$V_PM3^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S07', '^$V_PM3^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S10', '^$V_PM3^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S11', '^$V_PM3^', ^$ZA00_NUDOSS^) +
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('S13', '^$V_PM3^', ^$ZA00_NUDOSS^) -
			TOMEK.PIT_WAROSC_ZX8K_NUDOSS('SPP', '^$V_PM3^', ^$ZA00_NUDOSS^)
			,'FM9999999990.00') PINNE_3,
	
    TO_CHAR(ADD_MONTHS(TO_DATE('^$V_PM1^','YYYYMM'),1),'YYYY-MM') PMIES_1,
	TO_CHAR(ADD_MONTHS(TO_DATE('^$V_PM2^','YYYYMM'),1),'YYYY-MM') PMIES_2,
	TO_CHAR(ADD_MONTHS(TO_DATE('^$V_PM3^','YYYYMM'),1),'YYYY-MM') PMIES_3
	
FROM DUAL; 

COMMENT:
SELECT 'result:1|msg:ZNALEZIENI PRACOWNICY: ^$VROW^' OUT_COMMENT FROM DUAL;

STOP:
SELECT 'result:1|msg:PLIK NIE ZOSTA£ UTWORZONY' OUT_TERMINATE FROM DUAL WHERE '^$VROW^' = 0;
